### ISSUE TITLE
nativescript / angular error

### ISSUE THREAD

**Issue by kdcro101** [kdcro101/xmpp-bosh-client#3]
![image](https://user-images.githubusercontent.com/8890603/45829780-36c7a900-bd2e-11e8-8ef3-c0ce1d2db239.png)

_Originally posted by @weijyewang in https://github.com/kdcro101/xmpp-bosh-client/issues/1#issuecomment-423230619_

**Comment by kdcro101** [comment]
@weijyewang , @bclee92 ,

I have tested (again) angular import:
```
import { BoshClient } from 'xmpp-bosh-client/browser';
```

Everything works ok.

I see from error output image, you posted, that it breaks when module `events` is required.

Try browser standalone bundle by including `./node_modules/xmpp-bosh-client/browser-bundle/index.js` into your bundle (analog to including global js resources in `angular.json`

Objects are exported via BoshXMPP wrapper.

then you could access it via ambiental declaration:

```
declare var BoshXMPP: any;
// and create instance via
var client =  BoshXMPP.BoshClient(USERNAME, PASSWORD, URL);

```

**Comment by weijyewang** [comment]
This is all i got after trying out
![image](https://user-images.githubusercontent.com/8890603/45892709-7f00cd00-bdfb-11e8-8271-2996b69b76ad.png)

**Comment by kdcro101** [comment]
@weijyewang ,@bclee92 ,

Node modules aren't compatible with nativescript out-of-box.

Read [How to Use any npm Module with NativeScript](https://www.nativescript.org/blog/how-to-use-any-npm-module-with-nativescript)

.. and check [nativescript-nodeify](https://www.npmjs.com/package/nativescript-nodeify)

Let me know how it went.

**Comment by weijyewang** [comment]
@kdcro101  Thank you for your fast respond. I will try that out later.

For now I have created a [playground ](https://play.nativescript.org/?template=play-ng&tutorial=getting-started-ng&id=LSfBm1&v=2)that all of us can test and debug through our phone

Simply download the nativescript app from playstore and scan QR code to run it on your cell phone.

**Comment by kdcro101** [comment]
@weijyewang ,

You have same problems with nativescript that other user had with angular (that are fixed now).
Problem was in missing modules that are required by this module (events,http,https...). 
That is why browserify is needed to run in browser. These modules are native to node (no instalation is needed) but are missing in browser. That is what browserify is solving. It includes browser compatible implementation of these standard modules.

I see that you are having the same problems with nativescript.
Nativescript, probably, implements fs,events,https/http... modules using some javascript->native bridge therefore modules needs to be processed in similar manner as browserify does.

I would go [nativescript-nodeify](https://www.npmjs.com/package/nativescript-nodeify) way.

**Comment by weijyewang** [comment]
i just tried with the `nativescript-nodeify`, still the same problem
